version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      # - run:
      #     name: Run tests
      #     command: bundle exec rspec
