version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.3
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
      # - run:
      #     name: Run tests
      #     command: bundle exec rspec
